services:
  - type: web
    name: amazon-music-metadata-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # <--- FIXED PATH HERE
    envVars:
      - key: PORT
        value: 10000
