services:
  - type: web
    name: amazon-music-metadata-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: PORT
        value: 10000
