services:
  - type: web
    name: music-metadata-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api/app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music_metadata_db
          property: connectionString
